name: Build

on:
  push:
    branches: ["main", "vanilla/48-beta2", "gnome-48"]
  pull_request:

env:
  MESON_BUILD_DIR: _build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
      - uses: actions/checkout@v4

      - name: De-bloat stock image
        run: |
          rm -r /run/host${{ runner.tool_cache }}

      - name: switch-to-sid
        run: |
          mv /etc/apt/sources.list.d/vanilla-base.sources /etc/vanilla-base.sources.bak
          echo "deb http://deb.debian.org/debian sid main" > /etc/apt/sources.list.d/sid.list
          apt update

      - name: Install needed packages
        run: |
          DEBIAN_FRONTEND=noninteractive apt update
          DEBIAN_FRONTEND=noninteractive apt install -y \
            dpkg-dev \
            build-essential \
            debhelper-compat \
            desktop-file-utils \
            dh-sequence-gnome \
            gnome-settings-daemon-dev \
            gsettings-desktop-schemas-dev \
            gtk-doc-tools \
            libaccountsservice-dev \
            libadwaita-1-dev \
            libcolord-dev \
            libcolord-gtk4-dev \
            libcups2-dev \
            libgcr-4-dev \
            libgdk-pixbuf-2.0-dev \
            libgirepository1.0-dev \
            libglib2.0-dev \
            libgnome-bg-4-dev \
            libgnome-bluetooth-ui-3.0-dev \
            libgnome-desktop-4-dev \
            libgnome-rr-4-dev \
            libgnutls28-dev \
            libgoa-1.0-dev \
            libgoa-backend-1.0-dev \
            libgsound-dev \
            libgtk-4-dev \
            libgtop2-dev \
            libgudev-1.0-dev \
            libhandy-1-dev \
            libibus-1.0-dev \
            libjson-glib-dev \
            libkrb5-dev \
            libmalcontent-0-dev \
            libmm-glib-dev \
            libnm-dev \
            libnma-gtk4-dev \
            libpolkit-gobject-1-dev \
            libpulse-dev \
            libpwquality-dev \
            libsecret-1-dev \
            libsmbclient-dev \
            libsoup-3.0-dev \
            libudisks2-dev \
            libupower-glib-dev \
            libwacom-dev \
            libx11-dev \
            libxft-dev \
            libxi-dev \
            libxklavier-dev \
            libxml2-dev \
            libxml2-utils \
            locales \
            meson \
            polkitd \
            python3-dbusmock \
            shared-mime-info \
            tecla \
            tzdata \
            xvfb \
            wget \
            git

      - name: Build
        run: |
          meson setup $MESON_BUILD_DIR -Dprofile=development -Dwarning_level=2
          meson compile -C $MESON_BUILD_DIR 2>&1 | tee compilation.log

      - name: Run tests
        run: |
          export GSK_RENDERER=ngl
          meson test -C $MESON_BUILD_DIR --verbose --no-stdsplit --no-rebuild

      - name: Build debian package
        run: |
          wget https://github.com/deezhizyu/gnome-control-center/tarball/gnome-48
          mv gnome-48 ../gnome-control-center_48.0~99-orchid-stable.orig.tar.gz
          dpkg-buildpackage -b -uc -us
          tar cvf ../gnome-control-center.tar.xz ../*.deb

      - name: Calculate and Save Checksums
        run: |
          sha256sum /__w/gnome-control-center/gnome-control-center.tar.xz >> checksums.txt

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ./*.log
            ${{ env.MESON_BUILD_DIR }}/meson-logs/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        with:
          name: gnome-control-center
          path: |
            checksums.txt
            /__w/gnome-control-center/gnome-control-center.tar.xz

      - uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            /__w/gnome-control-center/gnome-control-center.tar.xz
            checksums.txt
